steps:
  - label: ":ruby: Ruby master-dev"
    image: "rubylang/ruby:master-dev"
    commands:
      - apt-get update && apt-get install -y libyaml-dev
      - bundle install
      - bundle exec rake

  # - label: ":ruby: Ruby {{matrix.ruby}}"
  #   image: "ruby:{{matrix.ruby}}"
  #   commands:
  #     - bundle install
  #     - bundle exec rake
  #   matrix:
  #     setup:
  #       ruby:
  #         - 3.5.0
