steps:
  - label: ":ruby: Ruby master-dev"
    commands:
      - apt-get update && apt-get install -y libyaml-dev
      - bundle install
      - bundle exec rake
    plugins:
      - docker#v5.13.0:
          image: "rubylang/ruby:master-dev"

  # - label: ":ruby: Ruby {{matrix.ruby}}"
  #   commands:
  #     - bundle install
  #     - bundle exec rake
  #   matrix:
  #     setup:
  #       ruby:
  #         - 3.5.0
  #   plugins:
  #     - docker#v5.13.0:
  #         image: "ruby:{{matrix.ruby}}"
