steps:
  # - label: ":ruby: Ruby 4.0"
  #   image: "ruby:4.0"
  #   commands:
  #     - bundle install
  #     - bundle exec rake

  - label: ":ruby: Ruby head"
    image: "rubylang/ruby:master-dev"
    commands:
      - apt-get update && apt-get install -y libyaml-dev
      - bundle install
      - bundle exec rake
